config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/goals/all' => 'goals#all'
  patch '/tasks/adduser' => 'tasks#adduser'
  get '/activeusers' => 'users#active'
  #get '/auth/facebook/callback' => 'sessions#fbcreate'
  get '/auth/github/callback' => 'sessions#ghcreate'
  
  resources :tasks
  resources :incentives
  resources :goals do
    resources :tasks, only: [:new, :index, :edit]
    resources :incentives, only: [:new, :index]
  end
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/incentive.rb
class Incentive < ApplicationRecord
    belongs_to :goal

    validate :max_tasks

    def max_tasks
        errors.add(:num_tasks, "must be less than or equal to total tasks in goal") if num_tasks > goal.tasks.count
    end

    def percent_complete
        100 * self.goal.tasks.where(done: true).count / self.num_tasks
    end

    def self.all_for_user(user_id)
        joins(goal: [:users]).where("users.id = ?", user_id).distinct
    end
end

app/controllers/incentives_controller.rb
class IncentivesController < ApplicationController

    before_action :set_incentive, only: [:show, :edit, :update, :destroy]
    
    def new
        if params[:goal_id] && goal = Goal.find_by_id(params[:goal_id])
            @incentive = goal.incentives.build
        else
            @incentive = Incentive.new
        end
    end

    def create
        @incentive = Incentive.new(incentive_params)

        if @incentive.save
            redirect_to incentive_path(@incentive)
        else
            render :new
        end
    end

    def index
        if params[:goal_id]
            goal = Goal.find_by_id(params[:goal_id])
            if goal
                @incentives = goal.incentives.all
            else
                redirect_to goals_path
            end
        else
            @incentives = Incentive.all_for_user(current_user[:id])
        end
    end

    def show
    end

    def edit
    end

    def update
        if @incentive.update(incentive_params)
            redirect_to incentive_path(@incentive)
        else
            render :edit
        end
    end

    def destroy
        @incentive.destroy
        redirect_to incentives_path
    end

    private

    def set_incentive
        @incentive = Incentive.find_by(id: params[:id])
        if !@incentive
            redirect_to incentives_path
        end
    end

    def incentive_params
        params.require(:incentive).permit(:description, :num_tasks, :goal_id)
    end
end

app/helpers/incentives_helper.rb
module IncentivesHelper
end

app/views/incentives/_incentive_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: incentive} %>

<%= form_for(incentive) do |f| %>

    <div class = "form-group col-md-6">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
    </div>

    <div class = "form-group col-md-6">
        <%= f.label :num_tasks, "How many tasks need to be finished?" %>
        <%= f.number_field :num_tasks, class: 'form-control' %>
    </div>

    <br><br>
    <div class = "form-group col-md-6">
        <%= f.label :goal, "Assign to a goal" %>
        <%= f.collection_select :goal_id, Goal.all, :id, :name, {prompt: true}, {class: 'form-control'} %>
    </div>

    <%= f.submit class: 'btn btn-dark' %>
<% end %>

app/views/incentives/_incentive_progress_bar.html.erb
<div class = "incentive" style = 
    "background: linear-gradient(to right, #28ad3c <%= incentive.percent_complete %>%, 
    #574745 <%= incentive.percent_complete %>%)">

    <strong><%= link_to incentive.description, incentive_path(incentive) %></strong>
     - <%= incentive.percent_complete %>% of <%= incentive.num_tasks %> task(s) toward goal 
    <%= link_to incentive.goal.name, goal_path(incentive.goal) %> has been met
</div>
<br>

app/views/incentives/edit.html.erb
<h1>Edit Incentive</h1>

<%= render :partial => "incentives/incentive_form", :locals => {incentive: @incentive} %>

app/views/incentives/index.html.erb
<h1>Progress toward incentives:</h1>

<% @incentives.each do |incentive| %>
   
    <%= render :partial => "incentives/incentive_progress_bar", :locals => {incentive: incentive} %>

<% end %>

app/views/incentives/new.html.erb
<h1>Create a new incentive</h1>

<%= render :partial => "incentives/incentive_form", :locals => {incentive: @incentive} %>

app/views/incentives/show.html.erb
<%= render :partial => "incentives/incentive_progress_bar", :locals => {incentive: @incentive} %>


<%= link_to "Edit Incentive", edit_incentive_path(@incentive), class: "btn btn-outline-dark" %>  

<%= link_to "Delete Incentive", incentive_path(@incentive), method: :delete, class: "btn btn-outline-dark" %>