config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/goals/all' => 'goals#all'
  patch '/tasks/adduser' => 'tasks#adduser'
  get '/activeusers' => 'users#active'
  #get '/auth/facebook/callback' => 'sessions#fbcreate'
  get '/auth/github/callback' => 'sessions#ghcreate'
  
  resources :tasks
  resources :incentives
  resources :goals do
    resources :tasks, only: [:new, :index, :edit]
    resources :incentives, only: [:new, :index]
  end
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    validates :description, presence: true
    
    belongs_to :goal
    belongs_to :user

    #accepts_nested_attributes_for :goal

    def goal_attributes=(attributes)
        goal = Goal.find_or_create_by(attributes)
        if goal.valid?
            self.goal = goal
        end
    end

    #scope :order_by_goal, -> {order(:goal.name)}

    scope :order_by_age, -> {order(:created_at)}

    scope :finished, -> {where(done: true)}
    scope :unfinished, -> {where(done: false)}


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :set_task, only: [:show, :edit, :update, :destroy]

    def new
        @goals = Goal.all_for_user(current_user[:id])
        if params[:goal_id] && goal = Goal.find_by_id(params[:goal_id])
            @task = goal.tasks.build
        else
            @task = Task.new
            @task.user = current_user
            @task.build_goal # build_goal because task belongs_to goal
        end
    end

    def create
        @task = current_user.tasks.build(task_params)

        if @task.save
            redirect_to task_path(@task)
        else
            @goals = Goal.all_for_user(current_user[:id])
            @task.build_goal
            render :new
        end
    end

    def index
        if params[:goal_id]
            goal = Goal.find_by_id(params[:goal_id])
            if goal
                @tasks = goal.tasks.order_by_age
            else
                redirect_to goals_path
            end
        else
            @tasks = current_user.tasks.order_by_age
        end
    end

    def show
    end

    def edit
        @goals = Goal.all_for_user(current_user[:id])
    end

    def update
        if @task.update(task_params)
            redirect_to task_path(@task)
        else
            render :edit
        end
    end

    def adduser
        @task = current_user.tasks.build(description: params[:description], done: false, goal_id: params[:goal_id])

        if @task.save
            redirect_to task_path(@task)
        else
            render :new
        end
    end

    def destroy
        if @task.goal.last_task? # if the last task is deleted, we need to delete the whole goal or stuff breaks
            @task.goal.incentives.each do |i|
                i.destroy
            end
            flash[:error] = "The goal #{@task.goal.name} has no more tasks, so it has been deleted."
            @task.goal.destroy
        end
        @task.destroy
        redirect_to tasks_path
    end

    private

    def set_task
        @task = Task.find_by(id: params[:id])
        if !@task
            redirect_to tasks_path
        end
    end

    def task_params
        params.require(:task).permit(:description, :done, :goal_id, goal_attributes: [:name, :accomplished])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

    def finished_status
        if @task.done 
            finished = "Yes"
        else 
            finished = "No"
        end
    "Finished? #{finished}"
    end
end

app/views/tasks/_task_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: task} %>

<%= form_for(task) do |f| %>
    <div class = "form-group col-md-6">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
        <br>

        <div class = "form-check">
            <%= f.check_box :done, class: 'form-check-input' %>
            <%= f.label :done, class: 'form-check-label' %>
        </div>
    </div>

    <div class = "form-group col-md-6">
        <%= f.label :goal_id, "Assign to a goal" %>
        <%= f.collection_select :goal_id, @goals, :id, :name, {prompt: true}, {class: 'form-control'} %>
    </div>



    <% if !params[:goal_id] %>
        <div class = "new_form_attribute col-5">
            <h4>Or add a new goal</h4>
            <%= f.fields_for :goal do |g| %>
                <div class = "form-group">
                    <%= g.label :name %>
                    <%= g.text_field :name, class: 'form-control' %>
                </div>
                Accomplished?<br>
                <div class = "form-check">
                    <%= g.radio_button :accomplished, true, class: 'form-check-input' %>
                    <%= g.label :accomplished, 'Yes', class: 'form-check-label' %>
                </div>
                <div class = "form-check">
                    <%= g.radio_button :accomplished, false, class: 'form-check-input' %>
                    <%= g.label :accomplished, 'No', class: 'form-check-label' %>
                </div>
            <% end %>
        </div>
    <% end %>

    <%= f.submit class: 'btn btn-dark' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render :partial => "tasks/task_form", :locals => {task: @task} %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<div class = "flash_errors">
    <%= flash[:error] %>
</div>

<ul>
<% @tasks.unfinished.each do |task| %>
   
        <li>
        <strong>Task:</strong> <%= link_to task.description, task_path(task) %>
        <br>
        <strong>Belongs to goal:</strong> <%= link_to task.goal.name, goal_path(task.goal) %>
        <br>
        </li>
    
<% end %>

<% @tasks.finished.each do |task| %>
   
        <li class = "finished">
        <strong>Task:</strong> <%= link_to task.description, task_path(task) %>
        <br>
        <strong>Belongs to goal:</strong> <%= link_to task.goal.name, goal_path(task.goal) %>
        <br>
        </li>
    
<% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a task</h1>

<%= render :partial => "tasks/task_form", :locals => {task: @task} %>

app/views/tasks/new.htnl.erb
<h1>Create a task</h1>

<%= form_for(@task) do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :done %>
    <%= f.check_box :done %>

    <%= f.label :goal %>
    <%= f.collection_select Goal.all :goal %>

    <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2> Task: <%= @task.description %> </h2>

<%= render partial: 'layouts/errors', locals: {object: @task} %>

<h5>
    Part of goal: <%= link_to @task.goal.name, goal_path(@task.goal) %>
    <br>
    <%= finished_status %>
</h5>

<br><br>
<%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-outline-dark" %>  

<%= link_to "Delete Task", task_path(@task), method: :delete, class: "btn btn-outline-dark" %>