config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/goals/all' => 'goals#all'
  patch '/tasks/adduser' => 'tasks#adduser'
  get '/activeusers' => 'users#active'
  #get '/auth/facebook/callback' => 'sessions#fbcreate'
  get '/auth/github/callback' => 'sessions#ghcreate'
  
  resources :tasks
  resources :incentives
  resources :goals do
    resources :tasks, only: [:new, :index, :edit]
    resources :incentives, only: [:new, :index]
  end
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal.rb
class Goal < ApplicationRecord
    has_many :tasks
    has_many :users, through: :tasks
    has_many :incentives

    validates :name, presence: true

    scope :finished, -> {where(accomplished: true)}
    scope :unfinished, -> {where(accomplished: false)}

    def percent_complete
        100 * self.tasks.where(done: true).count / self.tasks.count
    end

    def distinct_users
        self.users.distinct
    end

    def last_task?
        if self.tasks.count <= 1
            true
        else
            false
        end
    end

    def goal_cleanup
        self.incentives.each do |i|
            i.destroy
        end
        self.tasks.each do |t|
            t.destroy
        end
    end

    def self.all_for_user(user_id)
        joins(:users).where("users.id = ?", user_id).distinct
    end

    def self.all_for_others(user_id)
        joins(:users).where("users.id != ?", user_id).distinct
    end



end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

    before_action :set_goal, only: [:show, :edit, :update, :destroy]

    def new
        @goal = Goal.new
    end

    def create
        @goal = current_user.goals.build(goal_params)
        if @goal.save
            flash[:error] = "You must create at least one task for your goal."
            @task = @goal.tasks.build(description: "Placeholder task - replace this text with your description", user_id: current_user[:id], done: false)
            @task.save
            redirect_to edit_goal_task_path(@goal, @task)
        else
            render :new
        end
    end

    # index only shows goals for the current user.  all shows everybody else's goals.
    def index
        #@goals = Goal.all_for_user(current_user[:id])
        @unfinished = Goal.all_for_user(current_user[:id]).unfinished
        @finished = Goal.all_for_user(current_user[:id]).finished
    end

    def all
        #@goals = Goal.all_for_others(current_user[:id])
        @unfinished = Goal.all_for_others(current_user[:id]).unfinished
        @finished = Goal.all_for_others(current_user[:id]).finished
    end

    def show
    end

    def edit
    end

    def update
        if @goal.update(goal_params)
            redirect_to goal_path(@goal)
        else
            render :edit
        end
    end

    

    def destroy
        @goal.goal_cleanup
        @goal.destroy
        redirect_to goals_path
    end

    private

    def set_goal
        @goal = Goal.find_by(id: params[:id])
        if !@goal
            redirect_to goals_path
        end
    end

    def goal_params
        params.require(:goal).permit(:name, :accomplished)
    end

end

app/helpers/goals_helper.rb
module GoalsHelper

    def accomplished_status
        if @goal.accomplished
            "Accomplished!"
        else 
            "In progress - #{@goal.percent_complete}% done"
        end 
    end
    
end

app/views/goals/_goal_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: goal} %>

<%= form_for(goal) do |f| %>
    <div class = "form-group col-md-6">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <br>
        Accomplished?<br>
        <div class = "form-check">
            <%= f.radio_button :accomplished, true, class: 'form-check-input' %>
            <%= f.label :accomplished, 'Yes', class: 'form-check-label' %>
        </div>
        <div class = "form-check">
            <%= f.radio_button :accomplished, false, class: 'form-check-input' %>
            <%= f.label :accomplished, 'No', class: 'form-check-label' %>
        </div>
    </div>


    <br>

    <%= f.submit class: 'btn btn-dark' %>

<% end %>

app/views/goals/all.html.erb
<h1>Goals</h1>

<h5>These goals belong to users other than you.  
If you would like to help another user work on one of them, 
describe the task you will be working on to add yourself to the goal.  
You may add more tasks later.</h5>

<br>
<h5>In progress:</h5>

<table>
    <% @unfinished.each do |goal| %>
        <tr>
            <td>
                <%= form_tag tasks_adduser_url, :method => :patch do %>
                    <strong>Goal:</strong> <%= link_to goal.name, goal_path(goal) %><br>
                    <strong>Users:</strong> 
                        <% goal.distinct_users.each do |user| %>
                            <span class = "user_highlight"><%= user.username %></span>
                        <% end %>
                    <br>
                    <strong>Add Task:</strong> 
                    <%= hidden_field_tag 'goal_id', goal.id %>
                    <%= text_field_tag 'description', nil, placeholder: 'Describe your task here' %>
                    <%= submit_tag "Create task" %>
                <% end %>
                <br><br>
            </td>
                
        </tr>
    <% end %>
</table>

<br>
<h5>Accomplished!</h5>
<table>
    <% @finished.each do |goal| %>
        <tr>
            <td>
                <%= form_tag tasks_adduser_url, :method => :patch do %>
                    <strong>Goal:</strong> <%= link_to goal.name, goal_path(goal) %><br>
                    <strong>Users:</strong> 
                        <% goal.distinct_users.each do |user| %>
                            <span class = "user_highlight"><%= user.username %></span>
                        <% end %>
                    <br>
                    <strong>Add Task:</strong> 
                    <%= hidden_field_tag 'goal_id', goal.id %>
                    <%= text_field_tag 'description', nil, placeholder: 'Describe your task here' %>
                    <%= submit_tag "Create task" %>
                <% end %>
                <br><br>
            </td>
                
        </tr>
    <% end %>
</table>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<%= render :partial => "goals/goal_form", :locals => {goal: @goal} %>

app/views/goals/index.html.erb
<h1>Goals</h1>

<br>
<h5>In progress:</h5>
<% @unfinished.each do |goal| %>
    <%= link_to goal.name, goal_path(goal), class: "btn btn-info btn-lg" %>
    <br><br>
<% end %>

<br>
<h5>Accomplished!</h5>
<% @finished.each do |goal| %>
    <%= link_to goal.name, goal_path(goal), class: "btn btn-outline-dark btn-lg" %>
    <br><br>
<% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render :partial => "goals/goal_form", :locals => {goal: @goal} %>

app/views/goals/show.html.erb
<h2>Goal: <%= @goal.name %></h2>

<br>
<strong>Status: </strong>
<br>
    <%= accomplished_status %>
<br><br>

<strong>Tasks:</strong><br>
<% @goal.tasks.each do |task| %>
    <div class = "<%= 'finished' if task.done %>">
        <%= task.user.username %>: <%= link_to task.description, task_path(task) %>
    </div>
<% end %>
<br>

<strong>Incentives for this goal:</strong><br>
<% @goal.incentives.each do |incentive| %>
    <%= render :partial => "incentives/incentive_progress_bar", :locals => {incentive: incentive} %>
<% end %>

<%= link_to "New Task", new_goal_task_path(@goal), class: "btn btn-outline-dark" %>

<%= link_to "New Incentive", new_goal_incentive_path(@goal), class: "btn btn-outline-dark" %>

<%= link_to "Edit Goal", edit_goal_path(@goal), class: "btn btn-outline-dark" %>

<%= link_to "Delete Goal", goal_path(@goal), method: :delete, class: "btn btn-outline-dark" %>